namespace Lumper.Generators.FGDGenerator;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Lumper.Lib.FGD;

public static class FGDGenerator
{
    private const string MomentumFGDInput = "../../../resources/momentum.fgd";
    private const string MomentumFGDOutput = "../../Lumper.Lib/FGD/MomentumFGD.g.cs";
    private const string GeneratedNamespace = "Lumper.Lib.FGD";
    private const string GeneratedClassName = "MomentumFGD";

    private static void Main()
    {
        string fgdSource = File.ReadAllText(MomentumFGDInput);
        List<RawEntity> rawEntities = FGDParser.Parse(fgdSource);

        var lookup = new Dictionary<string, RawEntity>(StringComparer.OrdinalIgnoreCase);
        foreach (RawEntity raw in rawEntities)
        {
            lookup[raw.Name] = raw;
        }

        var entities = lookup.Values
            .Select(ToRawEntity)
            .OrderBy(d => d.ClassName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        string code = GenerateSource(entities);

        string? outputDir = Path.GetDirectoryName(MomentumFGDOutput);
        if (!string.IsNullOrEmpty(outputDir))
        {
            _ = Directory.CreateDirectory(outputDir);
        }
        File.WriteAllText(MomentumFGDOutput, code);

        Console.WriteLine($"Generated {entities.Count} entities -> {MomentumFGDOutput}");
    }

    private static FGDEntityRaw ToRawEntity(RawEntity raw)
    {
        var properties = new Dictionary<string, FGDProperty>();
        foreach (RawProperty prop in raw.Properties)
        {
            properties[prop.Key] = new FGDProperty(
                prop.Key,
                prop.Type,
                prop.DisplayName ?? "",
                prop.DefaultValue ?? "",
                prop.Description ?? "",
                prop.Choices);
        }

        var inputs = new Dictionary<string, FGDInput>();
        foreach (RawProperty input in raw.Inputs)
        {
            inputs[input.Key] = new FGDInput(input.Key, input.Type, input.Description ?? "");
        }

        var outputs = new Dictionary<string, FGDOutput>();
        foreach (RawProperty output in raw.Outputs)
        {
            outputs[output.Key] = new FGDOutput(output.Key, output.Type, output.Description ?? "");
        }

        return new FGDEntityRaw(raw.Name, raw.ClassType, raw.Description ?? "", raw.InheritedBases, properties, inputs, outputs);
    }

    private static string GenerateSource(List<FGDEntityRaw> declarations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by Lumper.Generators/FGDGenerator. Do not edit by hand!");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedNamespace};");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"public static class {GeneratedClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly IReadOnlyDictionary<string, FGDEntityRaw> Declarations = new Dictionary<string, FGDEntityRaw>");
        sb.AppendLine("    {");

        foreach (FGDEntityRaw decl in declarations)
        {
            AppendDecl(sb, decl);
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, FGDEntity> Entities = FGD.ResolveInheritance(Declarations);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendDecl(StringBuilder sb, FGDEntityRaw decl)
    {
        string bases = string.Join(", ", decl.Bases.Select(Lit));

        sb.AppendLine(CultureInfo.InvariantCulture, $"        [{Lit(decl.ClassName)}] = new FGDEntityRaw(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            ClassName: {Lit(decl.ClassName)},");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            ClassType: {Lit(decl.ClassType)},");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            Description: {Lit(decl.Description)},");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            Bases: new string[] {{ {bases} }},");

        sb.AppendLine("            Properties: new Dictionary<string, FGDProperty>");
        sb.AppendLine("            {");
        foreach (KeyValuePair<string, FGDProperty> kv in decl.Properties)
        {
            AppendProperty(sb, kv.Key, kv.Value);
        }
        sb.AppendLine("            },");

        sb.AppendLine("            Inputs: new Dictionary<string, FGDInput>");
        sb.AppendLine("            {");
        foreach (KeyValuePair<string, FGDInput> kv in decl.Inputs)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"                [{Lit(kv.Key)}] = new FGDInput({Lit(kv.Value.Name)}, {Lit(kv.Value.ParameterType)}, {Lit(kv.Value.Description)}),");
        }
        sb.AppendLine("            },");

        sb.AppendLine("            Outputs: new Dictionary<string, FGDOutput>");
        sb.AppendLine("            {");
        foreach (KeyValuePair<string, FGDOutput> kv in decl.Outputs)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"                [{Lit(kv.Key)}] = new FGDOutput({Lit(kv.Value.Name)}, {Lit(kv.Value.ParameterType)}, {Lit(kv.Value.Description)}),");
        }
        sb.AppendLine("            }");

        sb.AppendLine("        ),");
    }

    private static void AppendProperty(StringBuilder sb, string key, FGDProperty prop)
    {
        if (prop.Choices.Count == 0)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"                [{Lit(key)}] = new FGDProperty({Lit(prop.Name)}, {Lit(prop.ValueType)}, " +
                $"{Lit(prop.DisplayName)}, {Lit(prop.DefaultValue)}, {Lit(prop.Description)}, new Dictionary<string, string>()),");
            return;
        }

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"                [{Lit(key)}] = new FGDProperty({Lit(prop.Name)}, {Lit(prop.ValueType)}, " +
            $"{Lit(prop.DisplayName)}, {Lit(prop.DefaultValue)}, {Lit(prop.Description)}, new Dictionary<string, string>");
        sb.AppendLine("                {");
        foreach (KeyValuePair<string, string> choice in prop.Choices)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"                    [{Lit(choice.Key)}] = {Lit(choice.Value)},");
        }
        sb.AppendLine("                }),");
    }

    private static string Lit(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}